execute pathogen#infect()

let mapleader = "\<Space>"

set nocompatible
filetype off

set foldmethod=indent
set foldnestmax=3
set nofoldenable

" Breaks line when it doesn't feet on pane
set linebreak
set wrap

syntax on
set mouse=a

set encoding=utf-8
set fileencodings=utf-8

set autoindent
set smartindent
set cindent
set background=dark
set expandtab
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set wildignore=*/.git/*,*/tmp/*,*.swp,*.pyc,*/node_modules/*
set ignorecase
set smartcase
set hlsearch
set incsearch
set shiftround
set history=1000
set undolevels=1000
set noswapfile
set nobackup
" set autochdir

set number
" set relativenumber
set cursorline
set linespace=3

set visualbell           " don't beep
set noerrorbells         " don't beep

let g:windowswap_map_keys = 0 "prevent default bindings

set laststatus=2
set t_Co=256

" Delete works on insert mode
set backspace=indent,eol,start

set colorcolumn=80

" Performance tricks
set ttyfast
set lazyredraw

set synmaxcol=512
syntax sync minlines=256

set regexpengine=1
set noshowcmd
set conceallevel=0
let g:vim_json_conceal=0


let g:netrw_dirhistmax = 0

" Makes aliases visible to vim :! command
" set shellcmdflag=-ic

" Remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e
set autowriteall
set autoread
set hidden
au FocusLost * silent! wa

so ~/.vim/plugins.vim
so ~/.vim/functions.vim
so ~/.vim/commands.vim
so ~/.vim/settings.vim

colorscheme solarized
