# Browser like tabs/window navigation
bind -r n previous-window
bind -r p next-window

# Rotate between windows
bind -r C-r last-window
bind -r Tab last-window

# Rename current window to current folder basename
bind N rename-window "#{b:pane_current_path}" \; display-message "Window renamed to #{b:pane_current_path}"

bind -r C-\\ switch-client -l

