# Add versions
# tap 'homebrew/versions'

# Add services
tap 'homebrew/services'

# Install cask with versions and fonts
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/homebrew-core'

# Install Apps
cask 'alfred'
cask 'appcleaner'

cask 'karabiner-elements'
cask 'messenger'
cask 'owasp-zap'
cask 'skitch'
cask 'skype'
cask 'spotify'
cask 'the-unarchiver'
cask 'whatsapp'
cask 'telegram'
cask 'tunnelblick'
cask 'spectacle'
cask 'bitwarden'
cask 'discord'
cask 'zoom'
cask 'izip'
cask 'veracrypt'
cask 'dbeaver-community'

# vsc*** for pairing :P
cask 'visual-studio-code'

# Browsers
cask 'firefox'
# cask 'google-chrome-canary'
cask 'brave-browser'
cask 'finicky'

# Install fonts
tap 'homebrew/cask-fonts'
cask 'font-source-code-pro-for-powerline'

# Install command line tools
brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'ctags'
brew 'editorconfig'
brew 'git'
brew 'htop'
brew 'hub'
brew 'imagemagick'
brew 'node'
brew 'openssl'
brew 'python3'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'shellcheck'
brew 'siege'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'vim'
brew 'jq'
brew 'ripgrep'
brew 'colima'
brew 'docker'
brew 'docker-compose'
brew 'diff-so-fancy'
brew 'entr' # watch files and execute a cmd
brew 'fd'
brew 'openjdk'
brew 'bitwarden-cli'
brew 'fzf' # fuzzy finder cli. Pipe options to it and select!
brew 'luarocks'

# Install neovim
tap 'neovim/neovim'
brew 'neovim'
