require('plugins')

require('functions/selected_content')
require('functions/vimscript_to_lua')

require('mappings/copy_paste')
require('mappings/visual_code_editing')
require('mappings/git')
require('mappings/fugitive')
require('mappings/panels')
require('mappings/defaults')
require('mappings/lsp')
require('mappings/buffers')
require('mappings/tabs')
require('mappings/macros')
require('mappings/netrw')
require('mappings/copilot')
require('mappings/ultisnips')
require('mappings/grep')

require('settings/vim')
require('settings/lsp')
require('settings/performance')
require('settings/navigation')
